### PR TITLE
Fix a code sample that uses angle brackets

### PR DESCRIPTION
**Pull request by rowild**
Angle brackets and their content are hidden in markdown. Therefore the passage is fixed according to how similar content is formatted in Providers/Service provider/index.md.

### CODE REVIEW

**Comment by rowild** [comment]
I don't know if this is of any relevance: When following the advise of using the sample code skeleton, I get this warning/error:

```
Method 'Aimeos\MShop\Plugin\Provider\Order\ProductItem::register()' is not compatible with method 'Aimeos\MShop\Plugin\Provider\Iface::register()'.intelephense(1038)
```

Aimeos 2020.7, php 7.3, TYPO3 9.5.21
Message created by Intelephense in VScode

Screen Shot 2020-11-04 at 23 53 16

**Comment by aimeos** [comment]
The return value type hint is missing:
```
public function register( \Aimeos\MW\Observer\Publisher\Iface $p ) : \Aimeos\MW\Observer\Listener\Iface
```
Can you please add:
```
 : \Aimeos\MW\Observer\Listener\Iface
```

**Comment by rowild** [comment]
Thank you! – Now it says
"Expected type '\Aimeos\MW\Observer\Listener\Iface'. Found 'void'"

"void" causes the previously mentioned warning again.

Screen Shot 2020-11-05 at 09 50 42

**Comment by aimeos** [comment]
Cause you must add `return $this`, which is also missing in the docs

**Comment by rowild** [comment]
Excellent, that works. I'll update in a moment.

**Comment by rowild** [comment]
Update done.

**Comment by aimeos** [comment]
Thanks a lot! :-)

**Pull request merged**
