### PR TITLE
Update manage-resources.md

### PR DESCRIPTION
**Pull request by nvdid**
Add example request body for adding categories to a product

Remove a repeated part in the page for simplicity and more readability

### CODE REVIEW

**Comment by aimeos** [comment]
Can you please add a separate example as the existing example is important to understand updating the product attributes.

**Comment by nvdid** [comment]
Sure I can. You are right, it is important. But I think the part is noted in the code above it and such repetitions make page longer and harder to read. Would you please take another look at the [page](https://aimeos.org/docs/2023.x/admin/jsonadm/manage-resources/#create-items) and tell me your final thoughts on it

**Comment by aimeos** [comment]
We've learnt ourselves that it's better to write more examples because many (junior) developers have problems abstracting and transfer the examples to what they need. Not everyone is as good as your are :-)

**Comment by nvdid** [comment]
You're right about how more examples are helpful to people. And you're the expert here, so I do as you prefer:)

**Comment by aimeos** [comment]
Thanks a lot! :-)

**Pull request merged**
